"""Create SKU table

Revision ID: 4d8eb6399364
Revises: 
Create Date: 2024-09-24 19:52:41.417729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8eb6399364'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku',
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.Text(), nullable=True),
    sa.Column('first_image_url', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_lvl_1', sa.Text(), nullable=True),
    sa.Column('category_lvl_2', sa.Text(), nullable=True),
    sa.Column('category_lvl_3', sa.Text(), nullable=True),
    sa.Column('category_remaining', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('rating_value', sa.Float(), nullable=True),
    sa.Column('price_before_discounts', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('price_after_discounts', sa.Float(), nullable=True),
    sa.Column('bonuses', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('similar_sku', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sku')
    # ### end Alembic commands ###
